import Link from 'next/link'

interface UsernameSetupBannerProps {
  username: string | null | undefined
}

// Detects auto-generated hunter_XXXXXXXX usernames and prompts user to set a real one
export default function UsernameSetupBanner({ username }: UsernameSetupBannerProps) {
  const isAutoGenerated = /^hunter_[a-z0-9]{8}$/.test(username ?? '')
  if (!isAutoGenerated) return null

  return (
    <div className="mb-5 border border-gold/50 bg-gold/5 p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3 animate-fade-up">
      <div>
        <div className="text-gold font-head font-bold text-sm tracking-wider flex items-center gap-2">
          <span>🎯</span> SET YOUR HUNTER NAME
        </div>
        <div className="text-text-muted font-head text-xs mt-1">
          You're currently showing as{' '}
          <span className="text-white font-mono bg-white/5 px-1.5 py-0.5">{username}</span>
          {' '}— give yourself a real identity before the hunt begins.
        </div>
      </div>
      <Link
        href="/settings"
        className="shrink-0 px-5 py-2.5 bg-gold text-navy font-head font-bold text-xs tracking-widest hover:bg-gold-dim transition-colors text-center"
      >
        UPDATE NAME →
      </Link>
    </div>
  )
}
