export interface EventTheme {
  id: string
  label: string
  description: string
  regionFocus: string
  avoidRegions: string
}

export const EVENT_THEMES: EventTheme[] = [
  {
    id: 'world_wonders',
    label: 'World Wonders',
    description: 'Famous landmarks and wonders that every explorer should know',
    regionFocus: 'Iconic world landmarks — one per country, spread across ALL continents and many different countries. Europe: Eiffel Tower (France), Big Ben/Tower Bridge (UK), Colosseum (Italy), Sagrada Família (Spain), Acropolis (Greece), Neuschwanstein Castle (Germany), Charles Bridge (Czech Republic), Anne Frank House (Netherlands), Palace of Culture (Poland), Blue Mosque (Turkey), Bratislava Castle (Slovakia), Hallstatt Village (Austria), Bran Castle (Romania); Asia: Great Wall (China), Taj Mahal (India), Mount Fuji (Japan), Angkor Wat (Cambodia), Petronas Towers (Malaysia), Burj Khalifa (UAE), Borobudur (Indonesia), Hagia Sophia (Turkey), Petra (Jordan), Bagan Temples (Myanmar), Sigiriya Rock (Sri Lanka), Potala Palace (Tibet/China), Marina Bay Sands (Singapore), Gyeongbokgung Palace (South Korea), Bayon Temple (Cambodia), Alhambra (Spain); Americas: Machu Picchu (Peru), Christ the Redeemer (Brazil), Statue of Liberty (USA), CN Tower (Canada), Chichen Itza (Mexico), Easter Island (Chile), Iguazu Falls (Argentina), Golden Gate Bridge (USA), Salar de Uyuni (Bolivia), Cartagena Old Town (Colombia), La Paz Cable Cars (Bolivia); Africa: Pyramids of Giza (Egypt), Victoria Falls (Zimbabwe), Kilimanjaro (Tanzania), Table Mountain (South Africa), Great Mosque of Djenne (Mali), Valley of the Kings (Egypt), Rock-Hewn Churches (Ethiopia), Volcanoes of Rwanda; Oceania: Sydney Opera House (Australia), Uluru/Ayers Rock (Australia), Milford Sound (New Zealand), Great Barrier Reef (Australia). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Avoid very obscure or hard-to-find locations — every place should be famous and exciting for young learners',
  },
  {
    id: 'animal_habitats',
    label: 'Animal Habitats',
    description: 'Places famous for incredible wildlife and nature',
    regionFocus: 'Locations known for amazing wildlife — one per country, spread across ALL continents. Africa: Serengeti (Tanzania), Masai Mara (Kenya), Kruger National Park (South Africa), Bwindi Forest (Uganda/gorillas), Volcanoes NP (Rwanda/gorillas), Etosha (Namibia/desert wildlife), Okavango Delta (Botswana), Simien Mountains (Ethiopia/gelada baboons), South Luangwa (Zambia/leopards), Hwange (Zimbabwe/elephants), Gorongosa (Mozambique), Omo Valley (Ethiopia), Dinder (Sudan), Comoé (Ivory Coast), Madagascar (lemurs), Masoala (Madagascar). Asia: Giant Panda Reserve/Chengdu (China), Jigokudani Snow Monkey Park (Japan), Ranthambore Tiger Reserve (India), Kerala Elephant Country (India), Chitwan Rhino Reserve (Nepal), Khao Yai (Thailand/elephants), Taman Negara (Malaysia/rainforest), Borneo rainforests (Malaysia/Indonesia/orangutans), Philippine Eagle Center (Philippines/tarsiers), Yala (Sri Lanka/leopards), Kaziranga (India/rhinos), Sundarbans (Bangladesh/tigers), Komodo Island (Indonesia/dragons). Americas: Amazon Rainforest (Brazil), Galápagos Islands (Ecuador), Pantanal Wetlands (Brazil/Bolivia), Manu NP (Peru/jaguars), Los Llanos (Venezuela/capybaras), Patagonia Penguins (Argentina), Costa Rica Cloud Forests, Manuel Antonio (Costa Rica), Corcovado (Costa Rica), Belize Barrier Reef, Monarch Butterfly Biosphere (Mexico), Yellowstone (USA/bison/wolves), Everglades (USA/alligators), Churchill (Canada/polar bears). Europe: Białowieża (Poland/European bison), Cairngorms (Scotland/red deer/eagles), Doñana (Spain/lynx), Camargue (France/flamingos), Vatnajökull Glacier (Iceland/Arctic foxes/puffins), Svalbard (Norway/polar bears), Bialystok (Poland/storks). Oceania: Great Barrier Reef (Australia), Daintree Rainforest (Australia), Kangaroo Island (Australia), Fiordland/Milford Sound (New Zealand), Kiwi sanctuaries (New Zealand), Sepik River (Papua New Guinea). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Avoid locations with no famous wildlife connection',
  },
  {
    id: 'capital_cities',
    label: 'Capital Cities',
    description: 'Learn capital cities from every continent',
    regionFocus: 'Capital cities from all continents — one per country: Paris (France), London (UK), Rome (Italy), Tokyo (Japan), Beijing (China), New Delhi (India), Canberra (Australia), Nairobi (Kenya), Cairo (Egypt), Brasília (Brazil), Ottawa (Canada), Mexico City (Mexico), Moscow (Russia), Ankara (Turkey), Bangkok (Thailand), Jakarta (Indonesia), Seoul (South Korea), Buenos Aires (Argentina), Pretoria (South Africa), Abuja (Nigeria), Berlin (Germany), Madrid (Spain), Athens (Greece), Warsaw (Poland), Lisbon (Portugal), Stockholm (Sweden), Oslo (Norway), Helsinki (Finland), Copenhagen (Denmark), Vienna (Austria), Brussels (Belgium), Bern (Switzerland), Dublin (Ireland), Reykjavik (Iceland), Budapest (Hungary), Prague (Czech Republic), Bucharest (Romania), Sofia (Bulgaria), Belgrade (Serbia), Zagreb (Croatia), Kyiv (Ukraine), Minsk (Belarus), Tallinn (Estonia), Riga (Latvia), Vilnius (Lithuania), Tbilisi (Georgia), Yerevan (Armenia), Baku (Azerbaijan), Astana (Kazakhstan), Islamabad (Pakistan), Dhaka (Bangladesh), Colombo (Sri Lanka), Kathmandu (Nepal), Ulaanbaatar (Mongolia), Phnom Penh (Cambodia), Vientiane (Laos), Hanoi (Vietnam), Yangon (Myanmar), Manila (Philippines), Wellington (New Zealand), Ottawa (Canada), Washington DC (USA), Lima (Peru), Bogotá (Colombia), Quito (Ecuador), Santiago (Chile), Asunción (Paraguay), Montevideo (Uruguay), La Paz (Bolivia), Caracas (Venezuela), Havana (Cuba), Kingston (Jamaica), San José (Costa Rica), Panama City (Panama), Addis Ababa (Ethiopia), Accra (Ghana), Dakar (Senegal), Kampala (Uganda), Dar es Salaam (Tanzania), Lusaka (Zambia), Harare (Zimbabwe), Maputo (Mozambique), Antananarivo (Madagascar), Algiers (Algeria), Tunis (Tunisia), Rabat (Morocco), Khartoum (Sudan), Amman (Jordan), Beirut (Lebanon), Jerusalem (Israel), Riyadh (Saudi Arabia), Muscat (Oman), Doha (Qatar), Dubai/Abu Dhabi (UAE), Tehran (Iran), Baghdad (Iraq)',
    avoidRegions: 'Use actual capital cities only — one capital per country',
  },
  {
    id: 'rivers_mountains',
    label: 'Rivers & Mountains',
    description: 'The world\'s great rivers, mountains and geographic features',
    regionFocus: 'Famous geographic features — one per country: Rivers: Nile (Egypt/Sudan/Uganda/Ethiopia), Amazon (Brazil/Peru/Colombia), Yangtze (China), Mississippi (USA), Rhine (Germany/Netherlands), Thames (UK), Seine (France), Danube (Austria/Hungary/Serbia/Romania), Ganges (India), Mekong (Vietnam/Cambodia/Laos/Thailand), Congo (DR Congo), Niger (Nigeria/Mali), Zambezi (Zambia/Zimbabwe), Murray-Darling (Australia), Ob (Russia), Volga (Russia), Yukon (Canada), Paraná (Argentina), Orinoco (Venezuela); Mountains and ranges: Everest (Nepal), K2 (Pakistan), Kilimanjaro (Tanzania), Mont Blanc (France/Italy), Matterhorn (Switzerland), Elbrus (Russia), Denali (USA), Aconcagua (Argentina), Chimborazo (Ecuador), Fuji (Japan), Olympus (Greece), Table Mountain (South Africa), Atlas Mountains (Morocco), Ethiopian Highlands, Drakensberg (South Africa), Blue Mountains (Australia), Southern Alps (New Zealand), Altai (Mongolia), Hindu Kush (Afghanistan), Karakoram (Pakistan); Other features: Grand Canyon (USA), Victoria Falls (Zimbabwe/Zambia), Angel Falls (Venezuela), Iguazu Falls (Argentina/Brazil), Niagara Falls (Canada/USA), Great Rift Valley (Kenya/Tanzania/Ethiopia), Dead Sea (Jordan/Israel), Baikal Lake (Russia), Caspian Sea (Kazakhstan), Great Lakes (Canada/USA), Atacama Desert (Chile), Sahara (multiple countries), Gobi Desert (Mongolia/China). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Focus on natural geographic features — not cities',
  },
  {
    id: 'ancient_history',
    label: 'Ancient History',
    description: 'Amazing ancient civilisations and archaeological sites kids love',
    regionFocus: 'Ancient sites and civilisations from around the world — one per country: Middle East and North Africa: Pyramids of Giza (Egypt), Valley of the Kings (Egypt — only use if Egypt not already used), Babylon ruins (Iraq), Persepolis (Iran), Palmyra ruins (Syria), Baalbek temples (Lebanon), Petra (Jordan), Hegra/Mada\'in Saleh (Saudi Arabia), Sana\'a Old City (Yemen), Istanbul/Constantinople (Turkey), Troy (Turkey — only if Turkey not already used); Europe: Colosseum (Italy), Pompeii (Italy — only if Italy not already used), Parthenon/Acropolis (Greece), Stonehenge (UK), Carnac megaliths (France), Lascaux caves (France — only if France not already used), Roman amphitheatre Pula (Croatia), Thracian tombs (Bulgaria), Dacian fortress (Romania), Mycenae (Greece — only if Greece not already used), Alhambra (Spain), Segovia aqueduct (Spain — only if Spain not already used), Bath Roman baths (UK — only if UK not already used), Hadrian\'s Wall (UK); Asia: Great Wall of China (China), Angkor Wat (Cambodia), Bagan temples (Myanmar), Borobudur (Indonesia), Hampi ruins (India), Ajanta caves (India — only if India not already used), Mohenjo-daro (Pakistan), Sigiriya fortress (Sri Lanka), Nara temples (Japan), Gyeongju (South Korea), Samarkand Registan (Uzbekistan); Africa: Meroe Pyramids (Sudan), Lalibela churches (Ethiopia), Aksum obelisks (Ethiopia — only if Ethiopia not already used), Great Zimbabwe (Zimbabwe), Leptis Magna (Libya), Carthage ruins (Tunisia), Timgad (Algeria), Volubilis (Morocco), Fasil Ghebbi fortress (Ethiopia); Americas: Machu Picchu (Peru), Chichen Itza (Mexico), Teotihuacan (Mexico — only if Mexico not already used), Tikal (Guatemala), Copán ruins (Honduras), Mesa Verde cliff dwellings (USA), Cahokia Mounds (USA — only if USA not already used), Nazca Lines (Peru — only if Peru not already used), Tiwanaku (Bolivia), Easter Island (Chile); Oceania: Aboriginal rock art Kakadu (Australia), Waitangi (New Zealand). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Use only well-known ancient sites that appear in school curricula',
  },
  {
    id: 'islands_oceans',
    label: 'Islands & Oceans',
    description: 'Amazing islands and ocean places around the world',
    regionFocus: 'Famous islands and ocean locations: Hawaii (USA), Galápagos (Ecuador), Iceland, Madagascar, Sri Lanka, New Zealand, Maldives, Fiji, Bali (Indonesia), Japan, Philippines, Cuba, Sardinia (Italy), Great Barrier Reef (Australia), Caribbean: Jamaica, Barbados, Trinidad and Tobago, Puerto Rico, Dominican Republic, Haiti, Martinique (France), Bahamas; Pacific: Tahiti (French Polynesia), Vanuatu, Tonga, Samoa, Niue, Palau, Micronesia; Indian Ocean: Seychelles, Mauritius, Réunion (France), Comoros, Zanzibar (Tanzania); Atlantic: Canary Islands (Spain), Azores (Portugal), Cape Verde, Bermuda, Faroe Islands (Denmark); Mediterranean: Malta, Cyprus, Corsica (France), Sicily (Italy), Crete (Greece), Rhodes (Greece), Santorini (Greece); Arctic/Antarctic: Svalbard (Norway), Greenland (Denmark); Southeast Asia islands: Borneo (Malaysia/Indonesia), Sumatra (Indonesia), Komodo (Indonesia). Use islands kids might have heard of.',
    avoidRegions: 'Avoid very tiny unknown islands — use well-known islands with clear identities',
  },
  {
    id: 'sports_events',
    label: 'Sports & Olympics',
    description: 'Famous sports venues and Olympic host cities',
    regionFocus: 'Famous sports venues and events — one per country, spread across ALL continents. Olympic host cities: Athens (Greece/ancient+modern Olympics), Paris (France/1900+1924+2024), London (UK/1908+1948+2012), Tokyo (Japan/1964+2020), Sydney (Australia/2000), Beijing (China/2008+2022), Rio de Janeiro (Brazil/2016), Barcelona (Spain/1992), Seoul (South Korea/1988), Montreal (Canada/1976), Mexico City (Mexico/1968), Munich (Germany/1972), Helsinki (Finland/1952), Stockholm (Sweden/1912), Los Angeles (USA/1984+2028), Rome (Italy/1960), Amsterdam (Netherlands/1928), Antwerp (Belgium/1920), Moscow (Russia/1980); Formula 1 circuits: Monaco, Monza (Italy), Silverstone (UK), Spa (Belgium), Suzuka (Japan), Interlagos (Brazil), Circuit of the Americas (USA), Yas Marina (UAE), Bahrain International Circuit, Singapore Marina Bay, Red Bull Ring (Austria), Hungaroring (Hungary), Zandvoort (Netherlands); Football/Soccer: Maracanã (Brazil), Wembley (UK), Santiago Bernabéu (Spain), Camp Nou (Spain), San Siro (Italy), Allianz Arena (Germany), Amsterdam Arena (Netherlands), Stade de France (France), Luzhniki (Russia), Azteca (Mexico), Estádio da Luz (Portugal), Celtic Park (Scotland), Signal Iduna Park (Germany); Cricket: MCG Melbourne (Australia), Lords (UK), Eden Gardens (India), Wankhede Mumbai (India), Newlands (South Africa), Kensington Oval (Barbados), Galle (Sri Lanka), Chittagong (Bangladesh), Sharjah (UAE); Rugby: Twickenham (UK), Millennium Stadium (Wales), Eden Park (New Zealand), Ellis Park (South Africa), Suncorp Stadium (Australia); Tennis: Wimbledon (UK), Roland Garros (France), US Open/Flushing Meadows (USA), Melbourne Park (Australia), Roland Garros; Athletics: Hayward Field (USA), Letzigrund (Switzerland), Olympic Stadium Lausanne (Switzerland); Motor racing: Le Mans (France), Daytona (USA), Indianapolis (USA), Nurburgring (Germany); Cycling: Mont Ventoux (France), Alpe d\'Huez (France), Strade Bianche Siena (Italy); Golf: Augusta National (USA), St Andrews (UK); Marathon: Boston (USA), Berlin (Germany), Chicago (USA), London (UK), New York (USA), Eldoret (Kenya/distance running capital). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Stick to well-known venues that hosted major international events',
  },
  {
    id: 'national_parks',
    label: 'National Parks',
    description: 'Stunning national parks and protected wild places',
    regionFocus: 'Famous national parks worldwide — spread across ALL continents. Africa: Masai Mara (Kenya), Amboseli (Kenya), Bwindi Impenetrable (Uganda), Volcanoes NP (Rwanda), Etosha (Namibia), Okavango Delta (Botswana), Simien Mountains (Ethiopia), Gorongosa (Mozambique). Americas: Iguaçu NP (Brazil), Amazon NP (Brazil), Los Glaciares/Patagonia (Argentina), Galápagos Islands (Ecuador), Manu NP (Peru), Corcovado (Costa Rica). Europe: Lake District (UK), Białowieża (Poland), Swiss National Park (Switzerland), Black Forest (Germany), Camargue (France), Pindus/Vikos (Greece), Rila (Bulgaria), Jotunheimen (Norway), Vatnajökull (Iceland). Asia: Jiuzhaigou (China), Zhangjiajie (China), Sagarmatha/Everest (Nepal), Chitwan (Nepal), Khao Yai (Thailand), Komodo (Indonesia), Taman Negara (Malaysia), Sundarbans (Bangladesh). Check the BANNED COUNTRIES list and never pick from those countries.',
    avoidRegions: 'Stick to internationally recognised parks that appear in geography textbooks — avoid tiny unknown reserves',
  },
  {
    id: 'food_culture',
    label: 'Food & Culture',
    description: 'Cities and places famous for food, festivals and culture',
    regionFocus: 'Places famous for food and culture — one per country: Europe: Paris (France/croissants, Louvre, fashion), Rome/Italy (pizza, pasta, Vatican), Barcelona (Spain/Gaudí, tapas, paella), Athens (Greece/gyros, mythology), Istanbul (Turkey/kebabs, bazaars, Bosphorus), Vienna (Austria/coffee houses, opera, Sachertorte), Munich (Germany/Oktoberfest, sausages, beer halls), Prague (Czech Republic/medieval old town, trdelník), Budapest (Hungary/goulash, baths, Danube), Lisbon (Portugal/pastéis de nata, fado music), Amsterdam (Netherlands/stroopwafel, canals, tulips), Brussels (Belgium/waffles, chocolate, comic strips), Copenhagen (Denmark/smørrebrød, Little Mermaid, hygge), Stockholm (Sweden/ABBA, meatballs, design), Kraków (Poland/pierogies, history), Edinburgh (Scotland/haggis, kilts, castle), Dublin (Ireland/stew, Guinness, cliffs), Reykjavik (Iceland/hot dogs, Northern Lights); Asia: Tokyo (Japan/sushi, anime, cherry blossom), Bangkok (Thailand/street food, temples, tuk-tuks), Mumbai (India/Bollywood, spices, street food), Singapore (hawker centres, multicultural food, Gardens by the Bay), Seoul (South Korea/kimchi, K-pop, palaces), Beijing/Chengdu (China/dumplings, spicy hotpot, panda), Hanoi (Vietnam/pho, banh mi, Old Quarter), Penang (Malaysia/Char Kway Teow, hawker heritage), Bali (Indonesia/nasi goreng, temple ceremonies, rice terraces), Colombo (Sri Lanka/curry, tea, elephants), Kathmandu (Nepal/dal bhat, mountains, monasteries); Middle East and Africa: Marrakech (Morocco/tagines, souks, medina), Cairo (Egypt/koshari, pyramids, bazaars), Addis Ababa (Ethiopia/injera, coffee ceremony, ancient history), Cape Town (South Africa/braai, wine, Table Mountain), Lagos (Nigeria/jollof rice, Afrobeats, Nollywood); Americas: Mexico City (Mexico/tacos, Day of Dead, murals), Rio de Janeiro (Brazil/carnival, samba, caipirinha), Buenos Aires (Argentina/asado, tango, steak), Lima (Peru/ceviche, oldest cuisine in Americas), Havana (Cuba/salsa, vintage cars, cigars), New Orleans (USA/jazz, Mardi Gras, gumbo), Montreal (Canada/poutine, French culture, festivals), Cartagena (Colombia/empanadas, arepas, colourful old town); Oceania: Melbourne (Australia/coffee culture, multicultural food, street art), Auckland (New Zealand/hangi, Māori culture, All Blacks). Always pick from a different country than BANNED COUNTRIES.',
    avoidRegions: 'Focus on places with exciting cultural identities that kids find fascinating',
  },
  {
    id: 'global_explorer',
    label: 'Global Explorer',
    description: 'A world tour hitting the most exciting places on every continent',
    regionFocus: 'One exciting, well-known landmark or place from each region: 4 from Europe, 4 from Asia, 3 from Americas, 3 from Africa, 3 from Oceania, 3 from Middle East — mix cities, nature, and historic sites kids will recognise',
    avoidRegions: 'Every location must be recognisable and appear in school geography textbooks',
  },
]

// 8 kid-friendly narrative styles — rotate by (roundNumber - 1) % 8
export const NARRATIVE_STYLES = [
  'Young explorer\'s adventure journal — excited, enthusiastic, like a kid sharing their most exciting discovery',
  'Friendly talking animal narrator — a curious parrot or wise owl describing their home country with fun facts',
  'Time capsule letter — written by a child from that country to their pen pal overseas, sharing what makes their home special',
  'Children\'s travel documentary — enthusiastic, wonder-filled, like a fun TV show for kids',
  'Geography teacher\'s exciting lesson — enthusiastic, packed with cool facts, making learning irresistible',
  'Postcard from a young adventurer — warm, personal, brimming with excitement about what they saw',
  'Storybook narrator — warm, imaginative, painting a vivid picture that invites young readers to visit',
  'World record announcer — enthusiastic superlatives about what makes this place the biggest, smallest, oldest, or most amazing',
]
