export const worldChaseMapStyle: google.maps.MapTypeStyle[] = [
  { elementType: 'geometry', stylers: [{ color: '#1a2035' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#1a2035' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#8a9bb5' }] },
  { featureType: 'administrative.country', elementType: 'labels.text.fill', stylers: [{ color: '#c0cce0' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#d0dcea' }] },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi', elementType: 'labels.text.fill', stylers: [{ color: '#8899aa' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#1a2e1a' }] },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#2a3255' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#1a2245' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#2e3d6b' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#3a4d88' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#f5c518' }] },
  { featureType: 'road.local', elementType: 'labels.text.fill', stylers: [{ color: '#7a8aa0' }] },
  { featureType: 'transit', elementType: 'geometry', stylers: [{ color: '#2a3555' }] },
  { featureType: 'transit.station', elementType: 'labels.text.fill', stylers: [{ color: '#d59563' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0d1f3a' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#4a6080' }] },
  { featureType: 'landscape.natural', elementType: 'geometry', stylers: [{ color: '#1e2d1e' }] },
]
